### ISSUE TITLE
Repository status.

### ISSUE THREAD

**Issue by fxrstor** [Ruzie/WinInternal#1]
Hi.
This is a very old repository but you're account is active, switched to Linux.
Will this repository be updated with more functions and classes (obv ig no, then archive this repo.)?

Thanks.

**Comment by rilysh** [comment]
Hi - I don't think I'll ever going to work on this, so no, there will not going be any updates in the future. However, I tend to keep repositories open, just in case, if someone wants to merge their PR to them or have issues (creating an issue, and such).
